- topics/servers_raw-sockets.md
> Fixed ByteReadChannel/ByteWriteChannel KDoc links

- topics/Creating_custom_features.md
- topics/Serving_Static_Content.md
- topics/Testing.md
- topics/authentication.md
- topics/autoheadresponse.md
- topics/docker.md
- topics/dropwizard_metrics.md
- topics/features_locations.md
- topics/google-app-engine.md
- topics/gson.md
- topics/html_dsl.md
- topics/jackson.md
- topics/json-feature.md
- topics/lib.md
- topics/sessions.md
- topics/ssl.md
- topics/timeout.md
Added links to runnable code examples from corresponding topics, an example:
> KTOR-1909 add links to examples

- codeSnippets/gradle.properties
- codeSnippets/snippets/async/build.gradle
- codeSnippets/snippets/auth/build.gradle
- codeSnippets/snippets/autohead/build.gradle
- codeSnippets/snippets/autoreload/build.gradle
- codeSnippets/snippets/custom-feature/build.gradle
- codeSnippets/snippets/docker/build.gradle
- codeSnippets/snippets/google-appengine-standard/build.gradle
- codeSnippets/snippets/gson/build.gradle
- codeSnippets/snippets/guice/build.gradle
- codeSnippets/snippets/html-widget/build.gradle
- codeSnippets/snippets/http2-push/build.gradle
- codeSnippets/snippets/jackson/build.gradle
- codeSnippets/snippets/jetty-embedded/build.gradle
- codeSnippets/snippets/jetty-war/build.gradle
- codeSnippets/snippets/jetty/build.gradle
- codeSnippets/snippets/locations/build.gradle
- codeSnippets/snippets/metrics/build.gradle
- codeSnippets/snippets/netty-embedded/build.gradle
- codeSnippets/snippets/netty/build.gradle
- codeSnippets/snippets/post/build.gradle
- codeSnippets/snippets/sessions/build.gradle
- codeSnippets/snippets/ssl/build.gradle
- codeSnippets/snippets/static-content/build.gradle
- codeSnippets/snippets/testable/build.gradle
- codeSnippets/snippets/timeout/build.gradle
- codeSnippets/snippets/tomcat-war/build.gradle
- changed ktor version to 1.5.3
- added links to space packages to fix the issue with 'kotlinx-html'
> Fix kotlinx html

- .gitignore
- codeSnippets/snippets/autohead/build.gradle
- codeSnippets/snippets/autohead/test/AuthHeadTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2514
> Tests for autohead project 

- codeSnippets/snippets/autoreload/build.gradle
- codeSnippets/snippets/autoreload/src/test/kotlin/AutoReloadTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2515
> Tests for autoreload project 

- ktor.tree
- topics/Configurations.xml
- topics/containers.md
- topics/gradle-application-plugin.md
- topics/heroku.md
- topics/maven-assembly-plugin.md
Created tutorials showing how to use the Gradle Application plugin and Maven Assembly plugin to package and run a Ktor application.
> Deployment gradle maven

- .idea/.gitignore
- .idea/ktor-documentation.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- codeSnippets/snippets/client-download-file/build.gradle
- codeSnippets/snippets/client-download-file/src/Downloader.kt
- codeSnippets/snippets/client-download-file/test/TestDownloader.kt
https://youtrack.jetbrains.com/issue/KTOR-2545
> Tests for client-download-file project

- codeSnippets/snippets/client-parallel-requests/build.gradle
- codeSnippets/snippets/client-parallel-requests/src/test/kotlin/ApplicationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2549
> Tests for client-parallel-requests project 

- codeSnippets/snippets/client-parallel-requests/src/test/kotlin/ApplicationTest.kt
- codeSnippets/snippets/client-timeout/build.gradle
- codeSnippets/snippets/client-timeout/src/test/kotlin/ApplicationTest.kt
- codeSnippets/snippets/e2e/build.gradle
- codeSnippets/snippets/e2e/src/main/kotlin/e2e/WithTestServer.kt
- codeSnippets/snippets/e2e/src/main/kotlin/e2e/server.kt
https://youtrack.jetbrains.com/issue/KTOR-2552
> Tests for client-timeout project

- codeSnippets/snippets/client-upload-file/build.gradle
- codeSnippets/snippets/client-upload-file/src/test/kotlin/ApplicationTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2557
> Tests for client-upload-file project

- codeSnippets/snippets/docker/build.gradle
- codeSnippets/snippets/docker/src/test/kotlin/DockerTest.kt
- codeSnippets/snippets/e2e/src/main/kotlin/e2e/gradle.kt
https://youtrack.jetbrains.com/issue/KTOR-2559
> Tests for docker project

- codeSnippets/snippets/download-file/build.gradle
- codeSnippets/snippets/download-file/src/test/kotlin/com/example/DownloadFileTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2575
> Tests for download-file project 

- codeSnippets/snippets/client-logging/src/test/kotlin/com/example/ApplicationTest.kt
- codeSnippets/snippets/client-parallel-requests/src/test/kotlin/ApplicationTest.kt
- codeSnippets/snippets/client-timeout/src/test/kotlin/ApplicationTest.kt
- codeSnippets/snippets/client-upload-file/src/test/kotlin/ApplicationTest.kt
- codeSnippets/snippets/docker/src/test/kotlin/DockerTest.kt
- codeSnippets/snippets/e2e/src/main/kotlin/e2e/TestServer.kt
- codeSnippets/snippets/e2e/src/main/kotlin/e2e/gradle.kt
- codeSnippets/snippets/embedded-server/build.gradle
- codeSnippets/snippets/embedded-server/src/test/kotlin/EmbeddedServerTest.kt
- codeSnippets/snippets/engine-main/build.gradle
- codeSnippets/snippets/engine-main/src/test/kotlin/EngineMainTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2587
> Tests for embedded-server and engine-main projects 

- codeSnippets/snippets/freemarker/build.gradle
- codeSnippets/snippets/freemarker/src/test/kotlin/FreeMarkerTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2594
> Tests for freemarker project

- topics/intellij-idea.xml
re: https://twitter.com/JetBrainsKtor/status/1386610606107766785
> Clarify that Ktor plugin is only supported in Ultimate

- ktor.tree
- topics/openapi_swagger.md
Docs for generating project from openapi definitions. Probably, it needs rephrasing.
> Add OpenApi/Swagger doc

- codeSnippets/snippets/html/build.gradle
- codeSnippets/snippets/html/src/test/kotlin/HtmlTest.kt
https://youtrack.jetbrains.com/issue/KTOR-2609
> Tests for html project

- topics/mustache.md
I found some duplicated text while reading the docs.
> Typo: fix duplicated text in mustache.md

- topics/features_auth.md
Fix [KTOR-2430](https://youtrack.jetbrains.com/issue/KTOR-2439)
> KTOR-2439 Document Bearer Auth Provider for Client

- topics/data-conversion.md
This pull request shows changes in line 117, but I didn't change anything there.
> Remove wrong word

- topics/fatjar.md
Added Instruction for Gradle (Kotlin)
> Update fatjar.md for Gradle (Kotlin)

- codeSnippets/snippets/e2e/README.md
https://youtrack.jetbrains.com/issue/KTOR-3451
> Code snippets - project e2e can't run

- codeSnippets/snippets/auth-oauth-google/src/main/kotlin/com/example/Application.kt
- codeSnippets/snippets/auth-oauth-google/src/test/kotlin/ApplicationTest.kt
- topics/oauth.md
- topics/sessions.md
Added the `state` parameter to redirect users back to the protected page.
> KTOR-5251 use the 'state' parameter to redirect users

- topics/Routing_in_Ktor.md
[Design](https://youtrack.jetbrains.com/issue/KTOR-5279/Design-for-regex-patterns-support-in-routing)
> KTOR-5567 Documentation for regex patterns in routing

- codeSnippets/snippets/_misc/EmbeddedServerConfigureEngine.kt
- topics/Configuration-file.topic
- topics/Engines.md
[KTOR-5603](https://youtrack.jetbrains.com/issue/KTOR-5603/Documentation-for-Add-shutdown-configuration-for-engine-in-stop-method)
> KTOR-5603 Shutdown configuration for engine

- topics/response.md
Update response.md to have more information to have more information on JSON object section. I had an issue because I already had content negotiation for the server and I couldn't import it. So after a bit of time I found out I need to add io.ktor:ktor-client-content-negotiation in gradle to make it work. This is just more of a suggestion so it's more user friendly and to have everything in one place. I know there's link on 66th line about ContentNegotiation for client but even that didn't help in timely manner.
> Update response.md to have more information

- topics/FAQ.topic
> KTOR-6064 Add NoTransformationFoundException to FAQ

- codeSnippets/settings.gradle.kts
- codeSnippets/snippets/data-conversion/README.md
- codeSnippets/snippets/data-conversion/build.gradle.kts
- codeSnippets/snippets/data-conversion/get.http
- codeSnippets/snippets/data-conversion/src/main/kotlin/dataconversion/Application.kt
- codeSnippets/snippets/data-conversion/src/main/resources/application.conf
- codeSnippets/snippets/data-conversion/src/main/resources/logback.xml
- codeSnippets/snippets/data-conversion/src/test/kotlin/dataconversion/ApplicationTest.kt
- topics/data-conversion.md
[KTOR-3623 Update documentation for the DataConversion plugin](https://youtrack.jetbrains.com/issue/KTOR-3623/Update-documentation-for-the-DataConversion-plugin)
[KTOR-4870 Add example project](https://youtrack.jetbrains.com/issue/KTOR-4870/Web-feedback-from-Data-conversion-https-ktor.io-docs-data-conversion.html)
- added a code sample for DataConversion as there was none
- referenced sample code in topic
- updated topic to improve structure and accuracy
Target release is `2.3.5`. I added a note about usage with Locations. Locations will be removed from the example for the next release.
> KTOR-3623 update docs for DataConversion plugin and add code sample

- codeSnippets/gradle.properties
- codeSnippets/snippets/aws-elastic-beanstalk/build.gradle.kts
- codeSnippets/snippets/deployment-ktor-plugin/build.gradle.kts
- codeSnippets/snippets/engine-main-custom-environment/build.gradle.kts
- codeSnippets/snippets/forwarded-header/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/gradle.properties
- codeSnippets/snippets/proguard/build.gradle.kts
- codeSnippets/snippets/tutorial-client-kmm/gradle/libs.versions.toml
- codeSnippets/snippets/tutorial-http-api/build.gradle.kts
- codeSnippets/snippets/tutorial-server-get-started-maven/pom.xml
- codeSnippets/snippets/tutorial-server-get-started/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-docker-compose/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-persistence-advanced/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-persistence/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive/build.gradle.kts
- codeSnippets/snippets/tutorial-website-static/build.gradle.kts
- codeSnippets/snippets/tutorial-websockets-server/build.gradle.kts
- help-versions.json
- project.ihp
- v.list
> Update Ktor version to 2.3.6

- codeSnippets/snippets/aws-elastic-beanstalk/build.gradle.kts
- codeSnippets/snippets/deployment-ktor-plugin/build.gradle.kts
- codeSnippets/snippets/engine-main-custom-environment/build.gradle.kts
- codeSnippets/snippets/forwarded-header/build.gradle.kts
- codeSnippets/snippets/proguard/build.gradle.kts
- codeSnippets/snippets/tutorial-http-api/build.gradle.kts
- codeSnippets/snippets/tutorial-http-api/src/main/kotlin/com/example/routes/CustomerRoutes.kt
- codeSnippets/snippets/tutorial-server-get-started/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-docker-compose/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-persistence-advanced/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-persistence/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive/build.gradle.kts
The BOM dependency is already described [here](https://ktor.io/docs/server-dependencies.html#dependencies-consistency).
- Removed `ktor_version` and updated the dependency names where the Ktor Gradle plugin is applied.
> Update Ktor dependencies where the Ktor Gradle plugin is applied

- codeSnippets/snippets/tutorial-website-interactive-persistence-advanced/src/main/kotlin/com/example/Application.kt
- codeSnippets/snippets/tutorial-website-interactive-persistence-advanced/src/main/kotlin/com/example/dao/DatabaseFactory.kt
Kotlin object is 'Singleton' by its nature, so I've found the name 'DatabaseFactory' as misleading - IMHO it should be changed to 'DatabaseSingleton' or 'DatabaseObject'
> Database persistence with exposed - 'DatabaseFactory' object name change to 'DatabaseSingleton'

- cfg/buildprofiles.xml
Fix [WRS-3590](https://youtrack.jetbrains.com/issue/WRS-3590) ktor.io/docs website doesn't appear in google search
> WRS-3590 Fix indexing configuration

- codeSnippets/snippets/auth-oauth-google/README.md
- codeSnippets/snippets/auth-oauth-google/src/main/kotlin/com/example/Application.kt
- topics/oauth.md
Fixed NPE for empty route, added route "home" to illustrate redirect
> KTOR-5273 Fix Sample for OAuth Plugin

- codeSnippets/gradle.properties
- codeSnippets/snippets/cors/src/main/kotlin/com/example/Application.kt
- codeSnippets/snippets/cors/src/test/kotlin/ApplicationTest.kt
- codeSnippets/snippets/e2e/build.gradle.kts
- codeSnippets/snippets/e2e/src/main/kotlin/e2e/WithTestServer.kt
- codeSnippets/snippets/e2e/src/main/kotlin/e2e/server.kt
- codeSnippets/snippets/embedded-server-multiple-connectors/src/main/kotlin/com/example/Application.kt
- codeSnippets/snippets/embedded-server-multiple-connectors/src/test/kotlin/ApplicationTest.kt
- codeSnippets/snippets/events/src/main/kotlin/com/example/Application.kt
- codeSnippets/snippets/events/src/main/kotlin/com/example/plugins/ApplicationMonitoringPlugin.kt
- codeSnippets/snippets/http2-push/src/main/kotlin/com/example/Main.kt
- codeSnippets/snippets/ssl-embedded-server/src/main/kotlin/com/example/Application.kt
- ktor.tree
- topics/Configuration-code.topic
- topics/Engines.md
- topics/cors.md
- topics/custom_plugins.md
- topics/events.md
- topics/migrating-3.md
- topics/shutdown-url.md
- topics/ssl.md
- v.list
[KTOR-6499](https://youtrack.jetbrains.com/issue/KTOR-6499/Documentation-for-Environment-Engine-Application-Design)
[Preview on staging](https://writerside.labs.jb.gg/staging/staging/ktor/3.0.0/migrating-3.html#applicationengine-applicationenvironment-and-application)
- added subsection "ApplicationEngine, ApplicationEnvironment, and Application﻿"
- added subsection "ktor-server-host-common module has been removed"
> KTOR-6499 Document changes in Environment,Engine, Application

- topics/auth.md
- topics/client_logging.md
- topics/client_retry.md
- topics/compression.md
- topics/content-encoding.md
- topics/response-validation.md
- topics/serialization-client.md
- topics/timeout.md
- topics/user-agent.md
- Logging - [KTOR-6624](https://youtrack.jetbrains.com/issue/KTOR-6624/Broken-link-in-Logging)
- Response validation - [KTOR-6590](https://youtrack.jetbrains.com/issue/KTOR-6590/Web-feedback-Broken-link-in-Response-validation)
- a few more broken links in other topics
> Fix broken API links in topics

- topics/jwt.md
- topics/rsa-keys-generation.md
The RSA Keys Generation topic was contributed [KTOR-6641](https://youtrack.jetbrains.com/issue/KTOR-6641/Web-feedback-from-JSON-Web-Tokens-Add-a-new-topic-for-RSA-key-generation).
I additionally reworded some of the text and improved the formatting to match our style guide, including:
- Fixed auto-detected formatting issues.
- Added a link to the sample project.
- Added a link summary to the JWT topic (to be displayed in the topic link tooltip).
[Preview on staging](https://ktor.shared.aws.intellij.net/docs/rsa-keys-generation.html)
> Edit and format the RSA Key Generation topic

- codeSnippets/gradle.properties
- codeSnippets/snippets/aws-elastic-beanstalk/build.gradle.kts
- codeSnippets/snippets/deployment-ktor-plugin/build.gradle.kts
- codeSnippets/snippets/engine-main-custom-environment/build.gradle.kts
- codeSnippets/snippets/forwarded-header/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/gradle.properties
- codeSnippets/snippets/proguard/build.gradle.kts
- codeSnippets/snippets/tutorial-client-kmm/gradle/libs.versions.toml
- codeSnippets/snippets/tutorial-http-api/build.gradle.kts
- codeSnippets/snippets/tutorial-server-get-started-maven/pom.xml
- codeSnippets/snippets/tutorial-server-get-started/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-docker-compose/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-persistence-advanced/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-persistence/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive/build.gradle.kts
- codeSnippets/snippets/tutorial-website-static/build.gradle.kts
- codeSnippets/snippets/tutorial-websockets-server/build.gradle.kts
- help-versions.json
- project.ihp
- v.list
- update the Ktor version in gradle.properties
- update the Ktor gradle plugin version
- update the version switcher
> Update Ktor version from 2.3.7 to 2.3.8

- topics/FAQ.topic
I just saw the question asked again in Slack so decided to add it to the FAQ.
Also:
- Replaced the pronunciation to be represented phonetically, as Kay-tor doesn't make it obvious the [a] is pronounced as [e]
- Formatted the file to fix autodetected issues
> Add the meaning of the Ktor name in FAQ

- cfg/buildprofiles.xml
- cfg/google-analytics-code.html
- project.ihp
Fix test failures by applying the patch provided in [WH-5260](https://youtrack.jetbrains.com/issue/WH-5260/ktor.io-to-jetbrains.com-transition-move-docs).
> Apply patch to fix test failures

- codeSnippets/gradle.properties
- codeSnippets/snippets/aws-elastic-beanstalk/build.gradle.kts
- codeSnippets/snippets/deployment-ktor-plugin/build.gradle.kts
- codeSnippets/snippets/engine-main-custom-environment/build.gradle.kts
- codeSnippets/snippets/forwarded-header/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/gradle.properties
- codeSnippets/snippets/proguard/build.gradle.kts
- codeSnippets/snippets/tutorial-client-kmm/gradle/libs.versions.toml
- codeSnippets/snippets/tutorial-http-api/build.gradle.kts
- codeSnippets/snippets/tutorial-server-get-started-maven/pom.xml
- codeSnippets/snippets/tutorial-server-get-started/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-docker-compose/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-persistence-advanced/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-persistence/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive/build.gradle.kts
- codeSnippets/snippets/tutorial-website-static/build.gradle.kts
- codeSnippets/snippets/tutorial-websockets-server/build.gradle.kts
- help-versions.json
- project.ihp
- topics/releases.md
- v.list
- updated Ktor and Ktor plugin versions from `2.3.9` to `2.3.10`
- updated the version in the version switcher
- added a new table entry in `releases.md`
> Update Ktor version to 2.3.10 

- topics/client-timeout.md
[KTOR-6950](https://youtrack.jetbrains.com/issue/KTOR-6950) Timeout topic: Some links lead to 404 pages
> KTOR-6950 Update API links to HttpTimeoutConfig properties

- topics/server-create-http-apis.md
[KTOR-6967](https://youtrack.jetbrains.com/issue/KTOR-6967)
> KTOR-6967 Fix incorrect snippet in HTTP APIs tutorial

- topics/server-requests-and-responses.topic
Added a link to the "Create a RESTful API" tutorial in the "Next steps" section of the "Handle requests and generate responses" tutorial.
> Add a link to the next tutorial in "Handle requests and generate responses"

- topics/server-static-content.md
https://youtrack.jetbrains.com/issue/KTOR-7071
> Links 1 and 2 in the "Serving static content" topic lead to 404

- codeSnippets/gradle.properties
- codeSnippets/snippets/aws-elastic-beanstalk/build.gradle.kts
- codeSnippets/snippets/deployment-ktor-plugin/build.gradle.kts
- codeSnippets/snippets/engine-main-custom-environment/build.gradle.kts
- codeSnippets/snippets/forwarded-header/build.gradle.kts
- codeSnippets/snippets/legacy-interactive-website/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/gradle.properties
- codeSnippets/snippets/proguard/build.gradle.kts
- codeSnippets/snippets/tutorial-client-kmm/gradle/libs.versions.toml
- codeSnippets/snippets/tutorial-server-db-integration/build.gradle.kts
- codeSnippets/snippets/tutorial-server-docker-compose/build.gradle.kts
- codeSnippets/snippets/tutorial-server-get-started/build.gradle.kts
- codeSnippets/snippets/tutorial-server-websockets/build.gradle.kts
- codeSnippets/snippets/tutorial-website-static/build.gradle.kts
- codeSnippets/snippets/tutorial-websockets-server/build.gradle.kts
- help-versions.json
- project.ihp
- topics/releases.md
- v.list
- update Ktor version from `2.3.11` to `2.3.12`
- add a release entry
> Update Ktor version to 2.3.12 and add a release entry

- topics/server-integrate-database.topic
fix typo `Databse.connect()` to `Database.connect()`
> fix typo in configure database section of ktor server docs

- CONTRIBUTING.md
Change:
`https://github.com/ktorio/ktor-documentation/` to `https://github.com/ktorio/ktor-documentation.git`
> fix the upstream url inside CONTRIBUTING.md

- topics/server-sessions.md
Fix the `HmacSha265` algorithm to `HmacSha256`
> Update a typo in server sessions

- topics/client-response-validation.md
[KTOR-7269](https://youtrack.jetbrains.com/issue/KTOR-7269)
> KTOR-7269 Broken links in "Response validation"

- topics/server-integrate-database.topic
[KTOR-7248](https://youtrack.jetbrains.com/issue/KTOR-7248)
In this tutorial: https://ktor.io/docs/server-integrate-database.html#add-starter-code.
The TaskRepository interface does not match the sample code, it is missing the suspend keyword. I have fixed this.
> Fix: KTOR-7248 Methods in FakeTaskRepository in first iteration shouldn't have the suspend keyword

- topics/migrating-3.md
[KTOR-7444](https://youtrack.jetbrains.com/issue/KTOR-7444)
- updated the section in the migration guide 'Introduction of `ServerConfigBuilder`'
> KTOR-7444 Document renaming ApplicationProperties to ServerConfig

- renovate.json
[KTOR-7719](https://youtrack.jetbrains.com/issue/KTOR-7719) Prevent Renovate from spamming in YouTrack "VCS Changes" tab
> KTOR-7719 Disable changelogs fetching for Ktor

- codeSnippets/snippets/tutorial-server-docker-compose/Dockerfile
[KTOR-6176](https://youtrack.jetbrains.com/issue/KTOR-6176)
> KTOR-6176 Fix wrong port syntax in Dockerfile

- codeSnippets/gradle.properties
- codeSnippets/snippets/aws-elastic-beanstalk/build.gradle.kts
- codeSnippets/snippets/deployment-ktor-plugin/build.gradle.kts
- codeSnippets/snippets/engine-main-custom-environment/build.gradle.kts
- codeSnippets/snippets/forwarded-header/build.gradle.kts
- codeSnippets/snippets/legacy-interactive-website/build.gradle.kts
- codeSnippets/snippets/proguard/build.gradle.kts
- codeSnippets/snippets/server-websockets-sharedflow/build.gradle.kts
- codeSnippets/snippets/tutorial-client-kmm/gradle/libs.versions.toml
- codeSnippets/snippets/tutorial-server-db-integration/gradle/libs.versions.toml
- codeSnippets/snippets/tutorial-server-docker-compose/build.gradle.kts
- codeSnippets/snippets/tutorial-server-get-started/build.gradle.kts
- codeSnippets/snippets/tutorial-server-restful-api/build.gradle.kts
- codeSnippets/snippets/tutorial-server-routing-and-requests/build.gradle.kts
- codeSnippets/snippets/tutorial-server-web-application/build.gradle.kts
- codeSnippets/snippets/tutorial-server-websockets/build.gradle.kts
- codeSnippets/snippets/tutorial-website-static/build.gradle.kts
- help-versions.json
- project.ihp
- topics/releases.md
- v.list
- Update Ktor version from `3.0.2` to `3.0.3`.
- Add release details for `3.0.3`.
> Update Ktor version to 3.0.3

- topics/client-engines.md
- topics/client-serialization.md
> KTOR-5085 Update info about XML serialization support

- codeSnippets/snippets/upload-file/src/main/kotlin/uploadfile/UploadFile.kt
- topics/migrating-3.md
- topics/server-requests.md
[KTOR-8089](https://youtrack.jetbrains.com/issue/KTOR-8089)
> KTOR-8089 Document limit for receiving multipart/form-data

- ktor.tree
- topics/client-basic-auth.md
- topics/client-bearer-auth.md
- topics/client-call-id.md
- topics/client-digest-auth.md
- topics/server-call-id.md
Related to the changes made for [KTOR-7626](https://youtrack.jetbrains.com/issue/KTOR-7626)
> fix: Add missing `toc-title`s, required dependencies and reference links to similar topics

- topics/migrating-3.md
[KTOR-7861](https://youtrack.jetbrains.com/issue/KTOR-7861)
> KTOR-7861 Document AttributeKey type matching change in the migration guide

- topics/migrating-3.md
[KTOR-7547](https://youtrack.jetbrains.com/issue/KTOR-7547)
> KTOR-7547 Document removal of empty Maven artifact

- codeSnippets/snippets/tutorial-kotlin-rpc-app/build.gradle.kts
- codeSnippets/snippets/tutorial-kotlin-rpc-app/src/main/kotlin/Client.kt
- codeSnippets/snippets/tutorial-kotlin-rpc-app/src/main/kotlin/Server.kt
- codeSnippets/snippets/tutorial-kotlin-rpc-app/src/main/kotlin/model/PizzaShop.kt
- topics/tutorial-first-steps-with-kotlin-rpc.topic
[KTOR-8221](https://youtrack.jetbrains.com/issue/KTOR-8221)
- bump Ktor version to `3.0.3`
- bump `kotlinx.rpc` version to `0.51.0`
- fix missing imports in code example
- update code snippets and function names
> KTOR-8221 Update the "First steps with Kotlin RPC" tutorial

- topics/server-create-and-configure.topic
[KTOR-8161](https://youtrack.jetbrains.com/issue/KTOR-8161)
> fix: KTOR-8161 wrong lines shown in code-block and formatting issues

- topics/client-requests.md
The information about submitForm's content type was wrong.
Feel free to edit the PR.
> fix wrong explanation on submitForm content type

- topics/server-requests-and-responses.topic
[KTOR-7994](https://youtrack.jetbrains.com/issue/KTOR-7994)
> fix: KTOR-7994 Wrong code block shown in handle requests and responses

- codeSnippets/snippets/autoreload-embedded-server/src/main/kotlin/com/example/Application.kt
- topics/server-auto-reload.topic
[KTOR-8380](https://youtrack.jetbrains.com/issue/KTOR-8380)
> fix: KTOR-8380 Use workaround for auto reload in autoreload-embedded-server

- topics/server-compression.md
> Remove redundant repeated paragraph.

- cfg/buildprofiles.xml
- project.ihp
- topics/welcome.topic
Update the WRS version to the latest and make the following changes:
- add links with icons for GitHub and Slack channels in the footer
- remove empty `<secondary>` element that is no longer required in starting pages
- replace `<a>` with `<card>` elements in starting pages
> chore: update WRS version 

- topics/Whats-new-in-Ktor-3-2-0.md
- topics/client-dependencies.md
- topics/server-dependencies.topic
[KTOR-8530](https://youtrack.jetbrains.com/issue/KTOR-8530) 
- Add an entry in _What's new in Ktor 3.2.0_.
- Add a new section in Ktor Server's _Adding dependencies_ topic.
- Add new and missing sections in Ktor Client's _Adding dependencies_ topic.
- Fix topic name typo in _ktor.tree_
> KTOR-8530 Add documentation for version catalog support

- codeSnippets/snippets/auth-oauth-google/src/main/kotlin/com/example/oauth/google/Application.kt
- codeSnippets/snippets/auth-oauth-google/src/main/resources/application.conf
The OAuth google snippet requires these modifications to work.
> fix(snippet): Fix OAuth Google snippet

- topics/client-engines.md
- topics/client-supported-platforms.md
- topics/server-engines.md
- topics/server-platforms.md
**Description**:
Update CIO support to include Js and WasmJs in Ktor Client and Server engines documentation.
Additionally, improve structure and formatting in client-engines.md.
**Related tickets**:
[KTOR-7050](https://youtrack.jetbrains.com/issue/KTOR-7050) Documentation for Ktor client for Kotlin/Wasm
[KTOR-7728](https://youtrack.jetbrains.com/issue/KTOR-7728) Documentation for Client CIO engine support for wasm-js and js
[KTOR-8047](https://youtrack.jetbrains.com/issue/KTOR-8047) Documentation for Support CIO server on WasmJS and JS targets
> Update CIO support for Js and WasmJs

- codeSnippets/snippets/static-files/src/main/kotlin/com/example/Application.kt
- ktor.tree
- topics/server-static-content.md
- topics/whats-new-330.md
[KTOR-8726](https://youtrack.jetbrains.com/issue/KTOR-8726)
- Add a new sub-section in _Serving static content_ for _Custom fallback_
- Add code example to sample project and update snippet lines
- Create a new _What's new in Ktor 3.3.0_ topic with the documented change
> KTOR-8726 Add documentation for static content custom fallback

- topics/whats-new-330.md
[KTOR-8834](https://youtrack.jetbrains.com/issue/KTOR-8834)
> KTOR-8834 Add documentation for Jetty version upgrade

- topics/server-auto-reload.topic
- topics/whats-new-320.md
- topics/whats-new-330.md
[KTOR-8845](https://youtrack.jetbrains.com/issue/KTOR-8845)
- add note about regression and chapter with more info in "What's new in 3.2.0"
- confirm the current state and future plans in "What's new in 3.3.0"
- add a _Limitations_ section to the auto-reload topic
> KTOR-8845 Document limitations of auto-reload

- ktor.tree
- topics/client-webrtc.md
- topics/whats-new-330.md
[KTOR-8867](https://youtrack.jetbrains.com/issue/KTOR-8867)
- Add an entry in _What's new in Ktor 3.3.0_.
- Create a new topic _WebRTC client_ under _Setting up a client_.
> KTOR-8867 Add documentation for WebRTC client

- topics/client-bom-remover.md
- topics/client-custom-plugins.md
- topics/client-multiplatform.md
- topics/google-app-engine.md
- topics/heroku.md
- topics/server-auto-reload.topic
This PR fixes several small but important documentation errors that could confuse developers:
1. **Incorrect import statement in BOMRemover plugin example**
2. **Wrong function reference in custom client plugins documentation**  
3. **Unsafe environment variable handling in Heroku deployment guide**
**File:** `client-bom-remover.md`
**Issue:** The example shows importing `compression` instead of `bomremover`
**Before:**
```kotlin
import io.ktor.client.plugins.compression.*
```
**After:**
```kotlin
import io.ktor.client.plugins.bomremover.*
```
**File:** `client-custom-plugins.md`
**Issue:** Documentation refers to `createApplicationPlugin` instead of `createClientPlugin`
**Before:**
```
To use this configuration in a plugin, pass a configuration class reference to …
```
> fix(docs): correct API references and environment variable handling

- codeSnippets/snippets/_misc_client/ResponseTypes.kt
- topics/client-responses.md
[KTOR-7755](https://youtrack.jetbrains.com/issue/KTOR-7755) 
Add a new section in the client's _Receiving responses_ topic for receiving multipart form data.
> chore: feat: KTOR-7755 Add documentation for receiving multipart form data with Ktor client
