ktorio/ktor-documentation

- topics/default-request.md
I just came across this while reading through the docs
> Fix typo in default-request.md

- topics/http-client_multiplatform.md
These tasks were broken for some time and it doesn't worth keeping them up to date on our side. Gradle config for samples was reworked here https://github.com/ktorio/ktor-samples/pull/89 and tasks are now obsolete.
> Remove experimental gradle tasks from doc

- ktor.tree
- redirection-rules.xml
Removed https://ktor.io/docs/examples.html and added a redirect to https://ktor.io/docs/samples.html
> KTOR-2325 remove Examples and add redirect

- topics/micrometer_metrics.md
spelling: Prometeus > Prometheus
> Spelling fix in micrometer_metrics.md. Prometeus > Prometheus

- codeSnippets/snippets/client-download-file/src/Downloader.kt
- codeSnippets/snippets/client-upload-file/src/main/kotlin/com/example/Application.kt
- topics/request.md
- topics/response.md
Added the `onUpload`/`onDownload` functions to existing examples for uploading/downloading files and referenced them in docs.
> Add onUpload/onDownload examples

- topics/Serving_Static_Content.md
This is mentioned offhandedly in https://github.com/ktorio/ktor/issues/514 as a workaround solution.
This behavior is not called out in the docs anywhere and is very useful to know.
> Adding documentation for "wildcard" static file routing

- topics/cors.md
I renamed the `white list` to `allow list` to refer to the allowed HTTP CORS Methods.
> Using more incluside words for allowed methods

- topics/proguard.md
Updated:
* The new group ID for the `proguard-gradle` artifact.
* The latest ProGuard version.
* Link to the ProGuard Gradle plugin manual page.
* Use the correct Java library jars depending on Java version.
* URL to the latest sample version.
Related sample PR: https://github.com/ktorio/ktor-samples/pull/98
> Update ProGuard page

- topics/http-client_plugins.md
Fixes documentation link pointing to a non-existing packages; due to renaming `features` to `plugins`.
> Fix `standard plugins` link

- topics/json.md
This PR updates the the Ktor Clients "Json" page:
- `kotlinx.serialization` is referred to in full everywhere (`kotlinx` is not an abbreviation for `kotlinx.serialization` – we have about 50 other libraries starting with `kotlinx` :) )
- Headlines are restructured to first show the name of the library, and then the platforms for which they are available.
> Update headlines for Ktor Client / Json

- topics/creating_http_apis.md
Fixed typos in HTTP APIs hands-on (`topics/creating_http_apis.md`):
- One is in package name. It does not correspond to [configuration file in the template repo](https://github.com/ktorio/ktor-http-api-sample/blob/886214a11763eb0f35b88a0479a6d0d917923b15/src/main/resources/application.conf#L7).
- One is a dot instead of comma.
> Fixed typos

- topics/data-conversion.md
Update the examples of [ConversionService](https://github.com/ktorio/ktor/blob/0de7948fbe3f78673f4f90de9c5ea5986691819a/ktor-utils/common/src/io/ktor/util/converters/ConversionService.kt#L13) and [DelegatingConversionService](https://github.com/ktorio/ktor/blob/99d172d9f8df1e95c58d4335d599ff20ac0d29e6/ktor-utils/common/src/io/ktor/util/converters/DataConversion.kt#L73) so they match their signatures.
> Update ConversionService and DelegatingConversionService examples with their new signature

- topics/native_server.md
- make sure to mention the reverse proxy option for HTTPS
- mention that only the windows target is not supported, you can still develop on windows
> Make native server limitations a bit more clear

- topics/lib.xml
Small fix to follow changes in IDEA help (for 2021.3+).
> IDEA help page was renamed

- topics/migrating-2.md
Going through migration, found that Sessions dep mapping is missing in the guide https://ktor.io/docs/migrating-2.html
> Add Sessions dep mapping to 2.x migration guide

- topics/timeout.md
https://youtrack.jetbrains.com/issue/KTOR-4261/Explanation-on-request,-connection,-and-socket-missing-in-KDoc
"`requestTimeoutMillis` for a request timeout." does not add the valuable information of what a _request timeout_ even means – it requires readers to manually cross-reference to the listing at the top of the page, which seems like something that could easily be avoided by including the information right at this place. This PR addresses this.
> Inline explanations for request, connect, and socket timeouts

- codeSnippets/snippets/server-websockets/src/main/kotlin/com/example/Application.kt
`lastId` itself isn't reassigned - the integer inside `AtomicInteger` is mutated. Therefore `lastId` can be a `val`. This makes it clearer that `lastId` shouldn't be reassigned.
The Coroutines docs have an example where an `AtomicInteger` is defined using `val`
https://kotlinlang.org/docs/shared-mutable-state-and-concurrency.html#thread-safe-data-structures
```kotlin
val counter = AtomicInteger()
fun main() = runBlocking {
withContext(Dispatchers.Default) {
massiveRun {
counter.incrementAndGet()
}
}
println("Counter = $counter")
}
```
> change `AtomicInteger` property from `var` to `val`

- topics/websocket_extensions_api.md
`MyWebSocketException` should be named `MyWebSocketExtension` as in the previous example.
> Change wrong parameter in extensions example

- codeSnippets/snippets/proguard/proguard.pro
I was getting runtime crashes with after updating to Ktor 2.3.0, and it looks like the ProGuard rules needed a small update.
> Update ProGuard keep rules for Ktor 2.3.0

- topics/http-client_engines.md
It is not clear in the docs that Apache5 automatically has http/2 enabled by default. 
The docs suggest that it is disabled by default and can be enabled if you want to.
But for Apache5 engine the http1/http2 negotiation is automatically enabled.
> Update http-client_engines.md that explains default http/2 behaviour

- codeSnippets/gradle.properties
- codeSnippets/settings.gradle.kts
- codeSnippets/snippets/client-call-id/README.md
- codeSnippets/snippets/client-call-id/build.gradle.kts
- codeSnippets/snippets/client-call-id/src/main/kotlin/com/example/Application.kt
- codeSnippets/snippets/client-call-id/src/main/kotlin/com/example/CallIdService.kt
- codeSnippets/snippets/tutorial-client-kmm/shared/build.gradle.kts
- ktor.tree
- topics/call-id.md
- topics/client_call_id.md
- v.list
[KTOR-6156](https://youtrack.jetbrains.com/issue/KTOR-6156/Documentation-for-CallId-Feature-for-Client)
- added documentation for CallId client plugin
- created a new code snippet with example. The example uses a Ktor server to demonstrate how call ID is transferred between multiple calls
- added a link summary to the CallId server plugin doc
> KTOR-6156 docs for CallId client plugin

- topics/Engines.md
[KTOR-6332](https://youtrack.jetbrains.com/issue/KTOR-6332/Documentation-for-idle-timeout-configuration-in-Jetty-Server)
- added `idleTimeout` to the code example
- explained what it's used for
- added a reference to the config class
> KTOR-6332 add docs for idleTimeout config option for Jetty

- topics/proxy.md
See [ProxySupportCommon.kt#L21](https://github.com/ktorio/ktor/blob/491acd80bda5196a93b418d111ccda5da347fb0a/ktor-client/ktor-client-darwin/darwin/src/io/ktor/client/engine/darwin/ProxySupportCommon.kt#L21), SOCKS not supported by Darwin.
> There is no SOCKS proxy support on Darwin.

- topics/default_headers.md
[KTOR-6380](https://youtrack.jetbrains.com/issue/KTOR-6380/Documentation-for-Make-DefaultHeaders-plugin-Kotlin-native-compatible)
> KTOR-6380 update native server support for DefaultHeaders

- codeSnippets/snippets/tutorial-http-api/build.gradle.kts
- codeSnippets/snippets/tutorial-website-static/build.gradle.kts
- codeSnippets/snippets/tutorial-website-static/src/main/kotlin/com/example/plugins/Routing.kt
- codeSnippets/snippets/tutorial-websockets-server/build.gradle.kts
- topics/creating_http_apis.md
- topics/creating_static_website.md
- topics/creating_web_socket_chat.md
[KTOR-4118](https://youtrack.jetbrains.com/issue/KTOR-4118/The-generator-adds-the-jvm-suffix-to-all-dependencies)
Affected topics:
Creating HTTP APIs
- updated dependencies and list order in topic
Creating a static website
- updated dependencies and list order in topic
- replaced `static` function with `staticResources` ([KTOR-6414](https://youtrack.jetbrains.com/issue/KTOR-6414/Web-feedback-from-Creating-a-static-website-https-ktor.io-docs-creating-static-website.html))
Creating a Websocket chat
- updated dependencies and list order in topic
> KTOR-4118 and KTOR-6414 Update plugin dependencies that have the "-jvm" suffix

- topics/migrating-3.md
- topics/sessions.md
[KTOR-6449](https://youtrack.jetbrains.com/issue/KTOR-6449/Document-backward-compatibility-for-new-session-encryption)
Document changes in the session encryption method:
- add a new section in the Migration guide ([preview](https://writerside.labs.jb.gg/staging/staging/ktor/3.0.0/migrating-3.html#session-encryption-method-update))
- add a note to the Sessions topic ([preview](https://writerside.labs.jb.gg/staging/staging/ktor/3.0.0/sessions.html#sign_encrypt_session
))
> KTOR-6449 Document backward compatibility for new session encryption

- topics/connection-pooling-caching.md
- topics/docker-compose.md
- topics/interactive_website_add_persistence.md
[KTOR-6483](https://youtrack.jetbrains.com/issue/KTOR-6483/Web-feedback-Incorrect-code-snippet-displayed-in-Database-persistence-with-Exposed)
The `gradle.properties` file had changed some time ago and the code snippets were not updated in the following topics:
- Database persistence with Exposed (https://ktor.shared.aws.intellij.net/docs/interactive-website-add-persistence.html#add-dependencies)
- Connection pooling and caching (https://ktor.shared.aws.intellij.net/docs/connection-pooling-caching.html#add-dependencies)
- Docker Compose (https://ktor.shared.aws.intellij.net/docs/docker-compose.html#add_dependencies)
> KTOR-6483 fix outdated code snippets from gradle.properties

- topics/client-dependencies.md
[KTOR-6479](https://youtrack.jetbrains.com/issue/KTOR-6479/Web-feedback-Incorrect-snippets-are-displayed-in-Adding-client-dependencies)
As the `tutorial-client-kmm` code example has changed, the snippets in "Adding client dependencies" need to be updated as well.
Preview: https://writerside.labs.jb.gg/staging/staging/ktor/2.3.6/client-dependencies.html
> KTOR-6479 fix code snippets in "Adding client dependencies"

- topics/http-client_engines.md
I just playing around a bit with ktor, linux and the curl client.
After it failed a few times on the CI machine, I realized that I have to install the `libcurl-gnutls` version.
libcurl has different versions available. 
It also have the `openssl` and `nns` version.
While I can confirm that the `openssl` versions doesn't work, I don't know if it will work with the `nns` version.
Whatever, I think it make sense to document this 🙃
> Add libcurl-gnutls info to curl

- topics/jwt.md
Added the missing `-jvm` postfix for the dependencies used by Maven. 
Without this postfix, Maven cannot compile the project, as all classes etc. are missing from the default `ktor-server-auth-jwt` artifact.
> fix(jwt): Added -jvm postfix for Maven dependencies

- topics/lib.topic
- topics/releases.md
Based on the web feedback from [KTOR-6688](https://youtrack.jetbrains.com/issue/KTOR-6688/Ktor-Releases-Add-release-details) and [KTOR-6207](https://youtrack.jetbrains.com/issue/KTOR-6207/Web-feedback-List-releases-in-Ktor-releases).
Similarly to what Kotlin has done in their docs, I've added a table in a new section within "Ktor Releases", called "Release details". [See a preview on staging 2](https://writerside.labs.jb.gg/staging/staging/ktor/2.3.8/releases.html#release-details).
- the highlights only give a basic overview
- readers can see the full changelog on GitHub
- for major/feature versions there's also a link to the migration guide
Do you think anything else should be included?
> KTOR-6688 List Ktor releases 

- codeSnippets/snippets/tutorial-server-get-started/build.gradle.kts
- codeSnippets/snippets/tutorial-server-get-started/src/test/kotlin/com/example/ApplicationTest.kt
- topics/server_create_a_new_project.topic
[KTOR-6769](https://youtrack.jetbrains.com/issue/KTOR-6769)
The generated code doesn't create a sample test. Updated the procedure in "Write an integration test" to include creation of necessary files and folders.
Additionally, updated the code sample to include the correct tests from the tutorial.
> KTOR-6769 Fix discrepancies in the procedure for writing integration tests in the Get started tutorial

- codeSnippets/gradle.properties
- codeSnippets/snippets/aws-elastic-beanstalk/build.gradle.kts
- codeSnippets/snippets/deployment-ktor-plugin/build.gradle.kts
- codeSnippets/snippets/engine-main-custom-environment/build.gradle.kts
- codeSnippets/snippets/forwarded-header/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/gradle.properties
- codeSnippets/snippets/proguard/build.gradle.kts
- codeSnippets/snippets/tutorial-client-kmm/gradle/libs.versions.toml
- codeSnippets/snippets/tutorial-http-api/build.gradle.kts
- codeSnippets/snippets/tutorial-server-get-started-maven/pom.xml
- codeSnippets/snippets/tutorial-server-get-started/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-docker-compose/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-persistence-advanced/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-persistence/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive/build.gradle.kts
- codeSnippets/snippets/tutorial-website-static/build.gradle.kts
- codeSnippets/snippets/tutorial-websockets-server/build.gradle.kts
- help-versions.json
- project.ihp
- topics/releases.md
- v.list
- updated Ktor and Ktor plugin version in examples
- updated project version and version picker (change not reflected on staging)
- added an entry to the Releases topic ([preview](https://ktor.shared.aws.intellij.net/docs/releases.html))
> Release docs for Ktor version 2.3.9

- topics/Engines.md
- Choosing an engine
- [embeddedServer﻿](https://ktor.io/docs/engines.html#embeddedServer)
- [ApplicationEngine.Configuration](https://ktor.io/docs/engines.html#configure-engine)
> Fix broken API links in the "Choosing an engine" topic

- topics/releases.md
Link contained an erroneous greater than sign at the end of the URL.
> Fix 3.0.0-beta-1 migration guide link

- topics/server-create-a-new-project.topic
There is no indent for YAML file now, so I fixed it.
Link: https://ktor.io/docs/server-create-a-new-project.html
Screen shot:
> fix broken code block of application.yaml

- codeSnippets/snippets/tutorial-website-interactive-docker-compose/docker-compose.yml
In docker compose example in the official ktor documentation the port from docker compose configuration doesn't match the port in the source code:
https://github.com/ktorio/ktor-documentation/blob/70822c37b33979538ce08da44f7c93e0eb12ab3e/codeSnippets/snippets/tutorial-website-interactive-docker-compose/src/main/resources/application.conf#L13)
Can be confusing to someone who's reading the documentation
> Fix ports mapping in docker-compose.yml

- topics/client-serialization.md
Looks like including a snippet that has sub include elements with custom variables is not appending the correct variable.
Preview: https://writerside.labs.jb.gg/staging/staging/ktor/2.3.10/client-serialization.html
> KTOR-6974 Fix variables in code snippets in client serialization

- topics/client-timeout.md
[KTOR-6913](https://youtrack.jetbrains.com/issue/KTOR-6913) Update HttpTimeout limitations for Test Engine
[Preview](https://writerside.labs.jb.gg/staging/staging/ktor/2.3.10/client-timeout.html#limitations)
Also:
- replaced the list with a table for more clarity
> KTOR-6913 Add MockEngine timeout limitation

- codeSnippets/gradle.properties
- codeSnippets/snippets/aws-elastic-beanstalk/build.gradle.kts
- codeSnippets/snippets/deployment-ktor-plugin/build.gradle.kts
- codeSnippets/snippets/engine-main-custom-environment/build.gradle.kts
- codeSnippets/snippets/forwarded-header/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/gradle.properties
- codeSnippets/snippets/proguard/build.gradle.kts
- codeSnippets/snippets/tutorial-client-kmm/gradle/libs.versions.toml
- codeSnippets/snippets/tutorial-http-api/build.gradle.kts
- codeSnippets/snippets/tutorial-server-get-started-maven/pom.xml
- codeSnippets/snippets/tutorial-server-get-started/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-docker-compose/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-persistence-advanced/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive-persistence/build.gradle.kts
- codeSnippets/snippets/tutorial-website-interactive/build.gradle.kts
- codeSnippets/snippets/tutorial-website-static/build.gradle.kts
- codeSnippets/snippets/tutorial-websockets-server/build.gradle.kts
- help-versions.json
- project.ihp
- topics/client-timeout.md
- topics/releases.md
- v.list
- update the Ktor version and plugins from 2.3.10 to 2.3.11
- add a [release](https://writerside.labs.jb.gg/staging/staging/ktor/2.3.11/releases.html#release-details) entry
- update MockEngine support for Socket timeout in the [client-timeout](https://writerside.labs.jb.gg/staging/staging/ktor/2.3.11/client-timeout.html#limitations) topic
> Update Ktor version to 2.3.11

- codeSnippets/snippets/tutorial-server-web-application/README.md
- topics/server-integrate-database.topic
1. Fix the name of the code example for the "Integrate a database" tutorial.
2. Add a README.md file in the code example for the "Create a website" tutorial.
> Fix code example name and add a missing README

- topics/client-logging.md
[KTOR-5816](https://youtrack.jetbrains.com/issue/KTOR-5816) Ktor client with logback-classic on android produces compilation error on build
Added a sub-section with the SLF4J library as a recommendation for logging in Android.
> KTOR-5816 Add logging binding library recommendation for android

- topics/lib.topic
[KTOR-5759](https://youtrack.jetbrains.com/issue/KTOR-5759) Sessions: documentation snippet lacks import statement
> KTOR-5759 add missing imports in the plugin installation snippet for embeddedServer

- topics/server-create-restful-apis.topic
[KTOR-7180](https://youtrack.jetbrains.com/issue/KTOR-7180) 
Some dependency was missing in the **build.gradle.kts** to be able to use the Ktor client in tests. Adding `ktor-server-test-host` fixed it as recommended in the  [testing topic](https://ktor.io/docs/server-testing.html).
Additionally added some missing imports in the other code blocks.
> KTOR-7180 Add missing imports and dependencies in the "Create a RESTful API" tutorial

- topics/releases.md
Added a release entry for the new beta release in the "Releases" topic.
Documentation for this release is not available yet.
> Add a release entry for the `3.0.0-beta-2` release

- codeSnippets/gradle.properties
- codeSnippets/snippets/auth-jwt-hs256/build.gradle.kts
- codeSnippets/snippets/auth-jwt-rs256/build.gradle.kts
- codeSnippets/snippets/auth-oauth-google/build.gradle.kts
- codeSnippets/snippets/client-auth-oauth-google/build.gradle.kts
- codeSnippets/snippets/client-engine-js/build.gradle.kts
- codeSnippets/snippets/client-json-kotlinx/build.gradle.kts
- codeSnippets/snippets/client-testing-mock/build.gradle.kts
- codeSnippets/snippets/client-type-safe-requests/build.gradle.kts
- codeSnippets/snippets/client-validate-2xx-response/build.gradle.kts
- codeSnippets/snippets/client-websockets-serialization/build.gradle.kts
- codeSnippets/snippets/cors/build.gradle.kts
- codeSnippets/snippets/json-kotlinx-method-override/build.gradle.kts
- codeSnippets/snippets/json-kotlinx-openapi/build.gradle.kts
- codeSnippets/snippets/json-kotlinx/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/5_send_response/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/7_receive_request/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/gradle.properties
- codeSnippets/snippets/request-validation/build.gradle.kts
- codeSnippets/snippets/resource-routing/build.gradle.kts
- codeSnippets/snippets/server-websockets-serialization/build.gradle.kts
- codeSnippets/snippets/server-websockets-sharedflow/build.gradle.kts
- codeSnippets/snippets/tutorial-client-kmm/gradle/libs.versions.toml
- codeSnippets/snippets/tutorial-server-db-integration/build.gradle.kts
- codeSnippets/snippets/tutorial-server-docker-compose/build.gradle.kts
- codeSnippets/snippets/tutorial-server-restful-api/build.gradle.kts
- codeSnippets/snippets/tutorial-server-routing-and-requests/build.gradle.kts
- codeSnippets/snippets/tutorial-server-web-application/build.gradle.kts
- codeSnippets/snippets/tutorial-server-websockets/build.gradle.kts
- v.list
In some examples we are still using old versions of Ktor, so I've updated them to use the latest one.
Also updated Kotlin versions to `2.0.0` so they match the versions used in the project generator.
> Update Kotlin version to `2.0.0` and Ktor versions where applicable

- topics/server-create-a-new-project.topic
Go to declaration shortcut is Cmd+B
> doc: Fixed typos in shortcut keys.

- help-versions.json
The docs are already published at [https://ktor.io/docs/3.0.0-beta-2/welcome.html]( https://ktor.io/docs/3.0.0-beta-2/welcome.html) from the `3.0.0-beta-2` branch.
> Update the version switcher to show docs for `3.0.0-beta-2` instead of `3.0.0-beta-1`

- topics/client-create-and-configure.md
https://ktor.io/docs/client-create-and-configure.html#plugins
The code in the example in this section of the documentation is non-working - there are no closing brackets. I have corrected the link to the lines so that the code is correct.
> Fix ref to code on client-create-and-configure.md

- codeSnippets/snippets/migrating-express-ktor/1_hello/README.md
- codeSnippets/snippets/migrating-express-ktor/1_hello/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/1_hello_config/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/2_static/README.md
- codeSnippets/snippets/migrating-express-ktor/2_static/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/2_static/src/main/kotlin/com/example/Application.kt
- codeSnippets/snippets/migrating-express-ktor/3_router/README.md
- codeSnippets/snippets/migrating-express-ktor/3_router/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/3_router/request.http
- codeSnippets/snippets/migrating-express-ktor/3_router/src/main/kotlin/com/example/routes/Birds.kt
- codeSnippets/snippets/migrating-express-ktor/4_parameters/README.md
- codeSnippets/snippets/migrating-express-ktor/4_parameters/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/5_send_response/README.md
- codeSnippets/snippets/migrating-express-ktor/5_send_response/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/6_templates/README.md
- codeSnippets/snippets/migrating-express-ktor/6_templates/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/7_receive_request/README.md
- codeSnippets/snippets/migrating-express-ktor/7_receive_request/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/7_receive_request/src/main/kotlin/com/example/Application.kt
- codeSnippets/snippets/migrating-express-ktor/8_middleware/README.md
- codeSnippets/snippets/migrating-express-ktor/8_middleware/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/README.md
- topics/migration-from-express-js.topic
Made the following changes to the sample project:
- Updated `kotlin(jvm)` version to `2.0.0`
- Replaced `static` with `staticFiles`
- Replaced `Route` with `Routing`
- Added `README.md` files in the root and sub-projects.
Changes to the "Migrating from Express to Ktor" topic:
- Replaced `static` with `staticFiles`
- Replaced `Route` with `Routing`
- Formatted file to fix project warnings
- Edited Github links to include the project name and not use `<emphasis>`
- Used the `<tldr>` element to the top of the topic for code examples
> Update the `migrating-express-ktor` sample and relevant topic

- codeSnippets/snippets/forwarded-header/Dockerfile
- codeSnippets/snippets/tutorial-server-docker-compose/Dockerfile
- topics/docker-compose.topic
- topics/docker.md
Added disclaimer text for OpenJDK being deprecated, and added another stage to the Dockerfile for caching dependencies. Two stage Dockerfile is too slow to build, as we are downloading dependencies each time.
also please warn me if my english is too shit for this type of contribution
smooch
> KTOR-7313: Dockerfile in sample Docker Compose is based on deprecated and old OpenJDK.

- codeSnippets/snippets/google-appengine-standard/build.gradle.kts
- codeSnippets/snippets/google-appengine-standard/src/main/appengine/app.yaml
- topics/google-app-engine.md
The docs and code examples for deploying a Ktor server project to Google AppEngine currently demonstrates use of the `java11` run time environment. The java11 runtime will reach end of support within a few weeks (31 October 2024). (See the [Support Schedule](https://cloud.google.com/appengine/docs/standard/lifecycle/support-schedule#java) as published by Google.)
I've updated the example project to use the most recent support Java runtime (`java21`). This also requires use of the latest AppEngine plugin for Gradle, version 2.8.0. 
I've also made a few small revisions to the associated documentation to clarify a few items which I found confusing when I worked through this for my own project.
> Clarify Google AppEngine docs, support java21 runtime

- topics/server-sessions.md
Fix outdated reference link to SessionStorageMemory.kt (on GitHub) for the `Sessions` page on `ktor.io`
> Update SessionStorageMemory reference in server-sessions.md

- topics/server-integrate-database.topic
In Ktor docs postgres link is outdated I have updated with new one.
> Update server-integrate-database.topic (Postgres link)

- topics/server-serialization.md
Documentation change to reflect changes from https://github.com/ktorio/ktor/pull/4225
> KTOR-5085 Remove note about JVM-only support for XML serialization

- topics/server-create-websocket-application.topic
The `DefaultWebSocketServerSession.sendAllTasks` helper function is used in the code of the `Application.configureSockets` function, but it was not included in the topic. Because of its absence on the user side, the program code cannot even be compiled.
Before: 
After:
> Included the helper function in the WebSocket configuration snippet.

- codeSnippets/snippets/google-appengine-standard/build.gradle.kts
com.github.johnrengelman.shadow plugin has changed the core maintainer and has new coordinates: https://plugins.gradle.org/plugin/com.gradleup.shadow
for more info se: https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow
> chore: replace com.github.johnrengelman.shadow with com.gradleup.shadow

- codeSnippets/snippets/tutorial-client-kmm/gradle/libs.versions.toml
The latest version of coroutines is 1.9.0.
Currently the version in the sample is 2.0.0 which is not existing yet
> fix(deps): downgrade coroutines to 1.9.0

- topics/releases.md
- Listed `3.0.0-rc-1` to the Releases page.
- Included a link to the  migration guide for  both `3.0.0-rc-1` and `3.0.0-beta-2`.
> Add release details for 3.0.0-rc-1

- codeSnippets/snippets/json-kotlinx/src/test/kotlin/jsonkotlinx/ApplicationTest.kt
- codeSnippets/snippets/upload-file/src/test/kotlin/uploadfile/UploadFileTest.kt
- topics/migrating-3.md
- topics/migration-to-20x.md
- topics/server-testing.md
[KTOR-7495](https://youtrack.jetbrains.com/issue/KTOR-7495)
- Document the removal of `withTestApplication` and `withApplication` in the Migration guide.
- Update source in code blocks to point to the `snippets` folder on github `2.3.12` branch where the legacy testing API has been used. (Due to the removal of test functions that use the legacy testing API in the `3.0.0-rc-2` release.)
[Preview Migration Guide on Staging](https://ktor.shared.aws.intellij.net/docs/3.0.0-rc-2/migrating-3.html#withtestapplication-and-withapplication-have-been-removed)
> KTOR-7495 Document removal of `withTestApplication`

- topics/migrating-3.md
I noticed a very small typo when reading the migration guide.
`ApplciationEngine` should be `ApplicationEngine`.
> Fix typo in 3.0.x migration guide

- topics/server-static-content.md
[KTOR-7311](https://youtrack.jetbrains.com/issue/KTOR-7311) 
There are no API changes, so I just added a subsection in the **Serving static content** topic about automatic reloading in `staticZip()`.
Also included the missing API links to the main functions mentioned.
> Document staticZip support of automatic reloading

- codeSnippets/snippets/auth-jwt-rs256/src/main/kotlin/com/example/Application.kt
- codeSnippets/snippets/tutorial-server-db-integration/src/main/kotlin/com/example/plugins/Routing.kt
- codeSnippets/snippets/tutorial-server-docker-compose/src/main/kotlin/com/example/plugins/Routing.kt
- codeSnippets/snippets/tutorial-server-web-application/src/main/kotlin/com/example/plugins/Routing.kt
- codeSnippets/snippets/tutorial-server-websockets/src/main/kotlin/com/example/plugins/Routing.kt
- codeSnippets/snippets/webjars/src/main/kotlin/com/example/Application.kt
- topics/server-create-website.topic
- topics/server-webjars.md
[KTOR-2866](https://youtrack.jetbrains.com/issue/KTOR-2866)
In tutorial code examples, the `static` function was automatically created by the Ktor generator. The generator no longer uses the deprecated function, so the samples have been updated to reflect this change.
> KTOR-2866 Replace deprecated `static` function with `staticFiles` or `staticResources`

- topics/migrating-3.md
[KTOR-7605](https://youtrack.jetbrains.com/issue/KTOR-7605) TcpSocketBuilder.bind became suspend which breaks calling it in init block
Added a section to the migration guide that explains the change.
> KTOR-7605 Document change of server socket `.bind()` function

- codeSnippets/snippets/client-engine-winhttp/build.gradle.kts
Hi! I had issues with launching ./gradlew :tutorial-client-get-started:run and ./gradlew :tutorial-server-get-started:run 
the issue was: 
> FAILURE: Build failed with an exception.
> * Where:
Build file 'C:\Repositories\IdeaProjects\ktor-documentation\codeSnippets\snippets\client-engine-winhttp\build.gradle.kts' line: 5
> * What went wrong:
Error resolving plugin [id: 'org.jetbrains.kotlin.multiplatform', version: '2.0.0']
> The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version, so compatibility cannot be checked.
Sorry, this is my first attempt "contibution like" but i felt that it's weird that the project cannot be used out of box.
If i'm mistaken here just recent this merge :D
> Fixed build issues related to directly set kotlin version

- codeSnippets/gradle.properties
- codeSnippets/snippets/aws-elastic-beanstalk/build.gradle.kts
- codeSnippets/snippets/deployment-ktor-plugin/build.gradle.kts
- codeSnippets/snippets/engine-main-custom-environment/build.gradle.kts
- codeSnippets/snippets/forwarded-header/build.gradle.kts
- codeSnippets/snippets/legacy-interactive-website/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/gradle.properties
- codeSnippets/snippets/proguard/build.gradle.kts
- codeSnippets/snippets/server-websockets-sharedflow/build.gradle.kts
- codeSnippets/snippets/tutorial-client-kmm/gradle/libs.versions.toml
- codeSnippets/snippets/tutorial-server-db-integration/build.gradle.kts
- codeSnippets/snippets/tutorial-server-docker-compose/build.gradle.kts
- codeSnippets/snippets/tutorial-server-get-started/build.gradle.kts
- codeSnippets/snippets/tutorial-server-restful-api/build.gradle.kts
- codeSnippets/snippets/tutorial-server-routing-and-requests/build.gradle.kts
- codeSnippets/snippets/tutorial-server-web-application/build.gradle.kts
- codeSnippets/snippets/tutorial-server-websockets/build.gradle.kts
- codeSnippets/snippets/tutorial-website-static/build.gradle.kts
- help-versions.json
- project.ihp
- topics/releases.md
- v.list
- Bump Ktor version in `codeSnippets` from `3.0.0` to `3.0.1`.
- Add release details in the Releases topic.
- Update the version switcher to show the new version.
> Update Ktor version from 3.0.0 to 3.0.1 

- help-versions.json
- topics/releases.md
Added a release entry for `2.3.13` and updated the version in the switcher config.
> Add release details for 2.3.13 and update version switcher

- topics/client-request-retry.md
Fix HttpRequestRetry configuration class name and api docs link
[YouTrack Ticket](https://youtrack.jetbrains.com/issue/KTOR-7174/Retrying-failed-requests-a-broken-link-to-HttpRequestRetry.Configuration)
> KTOR-7174 Retrying failed requests: a broken link to HttpRequestRetry.Configuration

- codeSnippets/gradle.properties
- codeSnippets/snippets/aws-elastic-beanstalk/build.gradle.kts
- codeSnippets/snippets/client-engine-js/build.gradle.kts
- codeSnippets/snippets/deployment-ktor-plugin/build.gradle.kts
- codeSnippets/snippets/engine-main-custom-environment/build.gradle.kts
- codeSnippets/snippets/forwarded-header/build.gradle.kts
- codeSnippets/snippets/legacy-interactive-website/build.gradle.kts
- codeSnippets/snippets/migrating-express-ktor/gradle.properties
- codeSnippets/snippets/proguard/build.gradle.kts
- codeSnippets/snippets/server-websockets-sharedflow/build.gradle.kts
- codeSnippets/snippets/tutorial-client-kmm/gradle/libs.versions.toml
- codeSnippets/snippets/tutorial-server-db-integration/gradle/libs.versions.toml
- codeSnippets/snippets/tutorial-server-docker-compose/build.gradle.kts
- codeSnippets/snippets/tutorial-server-get-started/build.gradle.kts
- codeSnippets/snippets/tutorial-server-restful-api/build.gradle.kts
- codeSnippets/snippets/tutorial-server-routing-and-requests/build.gradle.kts
- codeSnippets/snippets/tutorial-server-web-application/build.gradle.kts
- codeSnippets/snippets/tutorial-server-websockets/build.gradle.kts
- codeSnippets/snippets/tutorial-website-static/build.gradle.kts
- help-versions.json
- project.ihp
- topics/releases.md
- v.list
- Upgraded Ktor version from `3.0.1` to `3.0.2`.
- Added release details in the `Releases` topic.
- Updated the version switcher version.
> Upgrade Ktor version to 3.0.2 and add release details

- codeSnippets/snippets/tutorial-server-docker-compose/Dockerfile
Fix `Dockerfile` missing copy of `gradle` folder to `cache` step leading to build failure.
[YouTrack ticker](https://youtrack.jetbrains.com/issue/KTOR-7565/Docker-script-compilation-errors-when-Gradle-version-catalog-is-used)
> KTOR-7565 Docker: script compilation errors when Gradle version catalog is used

- codeSnippets/snippets/tutorial-server-restful-api/src/main/kotlin/com/example/Application.kt
- codeSnippets/snippets/tutorial-server-restful-api/src/main/kotlin/com/example/Routing.kt
- codeSnippets/snippets/tutorial-server-restful-api/src/main/kotlin/com/example/Serialization.kt
- codeSnippets/snippets/tutorial-server-restful-api/src/test/kotlin/com/example/ApplicationTest.kt
- topics/server-create-restful-apis.topic
At first I wanted to address only the ticket issue.
But it turned out, the tutorial was a little bit outdated.
I have carefully read the content of the "How to create RESTful APIs in Kotlin with Ktor﻿" tutorial and tested each step.
Current version of the [Project wizzard](https://start.ktor.io/settings?name=ktor-sample&website=example.com&artifact=com.example.ktor-sample&kotlinVersion=2.1.0&ktorVersion=3.0.2&buildSystem=GRADLE_KTS&buildSystemArgs.version_catalog=true&engine=NETTY&configurationIn=YAML&addSampleCode=true&plugins=routing%252Ccontent-negotiation%252Cstatic-content) does not create a "plugins" package, so I changed the routes and packages in the article.
There was also one mistake in the package name.
And I added one additional step in "Create unit tests with Ktor client" …
> KTOR-7222 POST call in tutorial should return 201 Created status

- codeSnippets/snippets/embedded-server/src/main/kotlin/com/example/Application.kt
- topics/migrating-3.md
- topics/server-configuration-code.topic
[KTOR-7821](https://youtrack.jetbrains.com/issue/KTOR-7821)
- Documented removal of `commandLineEnvironment` in the Ktor 3.0 migration guide.
- Added a sub-section in "Configuration in code" for "Command-line configuration", explaining the usage of `CommandLineConfig`.
- Extended the `embedded-server` snippets project to include an example usage with command line config.
[Preview Migration Guide](https://ktor.staging.kotlin-aws.intellij.net/docs/migrating-3.html#CommandLineConfig)
[Preview Configuration in code](https://ktor.staging.kotlin-aws.intellij.net/docs/server-configuration-code.html#command-line)
> KTOR-7821 Document removal of `commandLineEnvironment` and usage of `CommandLineConfig`

- codeSnippets/snippets/micrometer-metrics/README.md
Minor fix related to micrometer-metrics `README.md` `Running a sample` instruction
> Fix micrometer-metrics running instruction in README.md

- topics/migrating-3.md
[KTOR-7560](https://youtrack.jetbrains.com/issue/KTOR-7560) 
Describe renaming from `content` to `rawContent` of `HttpResponse` in the migration guide
> KTOR-7560 Add the `content` property renaming of `HttpResponse` to the migration guide

- codeSnippets/snippets/html-templates/src/main/kotlin/com/example/Application.kt
- topics/server-html-dsl.md
This change adds an example of `PlaceholderList` class usage.
[YouTrack Ticket](https://youtrack.jetbrains.com/issue/KTOR-6782/Add-an-example-of-the-PlaceHolderList-class-usage)
> KTOR-6782 Add an example of the PlaceHolderList class usage

- codeSnippets/snippets/html-templates/src/test/kotlin/HtmlTest.kt
- codeSnippets/snippets/tutorial-server-restful-api/src/main/kotlin/com/example/Routing.kt
- topics/full-stack-development-with-kotlin-multiplatform.topic
1. Fixes a couple of tests that were failing due to recent updates in code examples. 
2. Fixes incorrect `src` path of the newly introduced `HttpClientManager.kt` in the full-stack with KMP tutorial.
> fix: Failing tests from recent changes and wrong src path provided in code-block

- codeSnippets/snippets/engine-main-custom-environment/src/main/resources/application.yaml
The environment variable is optional in the .conf file, and the code uses getPropertyOrNull, which implies the property is optional
> Made $KTOR_ENV environment variable optional

- topics/server-routing.md
`Regex`es in Kotlin are greedy by default, so it would match the last `hello` in the path.
> Fix server-routing.md documentation about greedy Regex

- topics/migrating-3.md
[KTOR-7672](https://youtrack.jetbrains.com/issue/KTOR-7672) 
Add an example in the relevant section in the Migration guide showcasing how to set `developmentMode` using `embeddedServer()` with `serverConfig`.
> KTOR-7672 Describe how to set developmentMode with embeddedServer in 3.*

- codeSnippets/snippets/upload-file/src/main/kotlin/uploadfile/UploadFile.kt
- topics/migrating-3.md
- topics/server-requests.md
[KTOR-7801](https://youtrack.jetbrains.com/issue/KTOR-7801) Document migrating from streamProvider to provider in multipart content
[Preview Migration guide](https://ktor.staging.kotlin-aws.intellij.net/docs/migrating-3.html#partdata-fileitem-streamprovider-is-deprecated)
[KTOR-7802](https://youtrack.jetbrains.com/issue/KTOR-7802) Add documentation and sample on how to save multipart form data in a file
[Preview Multipart form data](https://ktor.staging.kotlin-aws.intellij.net/docs/server-requests.html#form_data)
> KTOR-7801 and KTOR-7802 Document streamProvider deprecation and update the file upload example

- codeSnippets/snippets/tutorial-server-docker-compose/Dockerfile
The correct way to declare environment variables in a Dockerfile is using ENV key=value, with the key and value separated by =.
https://docs.docker.com/reference/build-checks/legacy-key-value-format/
> chore(snippets): update Dockerfile to use new key value format

- topics/server-create-a-new-project.topic
It seems that`Routing.kt` of https://ktor.io/docs/server-create-a-new-project.html#configure-static-content is broken due to lack of `}`. Besides that, I fix the indent as well.
> docs(server-create-a-new-project.topic): Fix unclosed brackets syntax error in Routing.kt

- topics/server-routing.md
The name of the routing tree builder has undergone multiple changes. As a result, the plugin object was renamed to `RoutingRoot` in [KTOR-7101](https://youtrack.jetbrains.com/issue/KTOR-7101).
- Updated the code snippet to ensure compatibility with this change.
- Removed the code block for Routing, as it is a commonly used name for a plugin.
This is my first contribution to the Ktor documentation, and you are welcome to edit it at any time.
> Correct the object from Routing to RoutingRoot

- codeSnippets/snippets/tutorial-server-get-started-maven/pom.xml
This PR fix [KTOR-7601](https://youtrack.jetbrains.com/issue/KTOR-7601/Update-dependency-and-Ktor-version-in-tutorial-server-get-started-maven)
* Following [Adding Ktor dependencies](https://ktor.io/docs/server-dependencies.html#add-ktor-dependencies), use platform-specific artifacts (i.e. `ktor-server-netty-jvm` and `ktor-server-test-host-jvm`) e81e3125594dc12857072dbc637c6013bda82bd2
* This is the same as the dependencies which I choose 'Build System' as 'Maven' in Ktor project create page https://start.ktor.io/settings
* ktor and kotlin versions are same as [gradle.properties](https://github.com/ktorio/ktor-documentation/blob/main/codeSnippets/gradle.properties) respectively cd4a883057f816ac0326c7bdbb8df2effb29aa96
After this change, successfully I could build and run the application …
> KTOR-7601: Fix dependencies for Maven build system tutorial

- codeSnippets/snippets/auth-digest/src/main/kotlin/authdigest/Application.kt
- codeSnippets/snippets/auth-form-session-nested/src/main/kotlin/com/example/Application.kt
- codeSnippets/snippets/auth-form-session/src/main/kotlin/com/example/Application.kt
- topics/server-auth.md
- topics/server-session-auth.md
- topics/server-sessions.md
**Description:**
Update code examples and auth-related topics to exclude deprecated `Principal` and `Credential` interfaces.
**Related issues:**
[KTOR-7627](https://youtrack.jetbrains.com/issue/KTOR-7627) 
[KTOR-7580](https://youtrack.jetbrains.com/issue/KTOR-7580)
> KTOR-7580 and KTOR-7627: Remove usage of `Principal` from auth docs

- topics/migrating-3.md
**Description**
Add a subsection in the migration guide for `SocketTimeoutException` becoming typealias.
**Related issue**
[KTOR-7822](https://youtrack.jetbrains.com/issue/KTOR-7822)
**Resources**
Slack ref: https://jetbrains.slack.com/archives/C07U498LLUR/p1732032882783529
Binary compatibility: https://stackoverflow.com/questions/14973380/what-is-binary-compatibility-in-java/14973523#14973523
> KTOR-7822 Document `SocketTimeoutException` becoming typealias

- codeSnippets/snippets/client-download-streaming/src/main/kotlin/com/example/Application.kt
- topics/client-responses.md
- topics/migrating-3.md
[KTOR-7210](https://youtrack.jetbrains.com/issue/KTOR-7210)
- Add a new section in the migration guide for the migration to the `kotlinx-io` library.
- Add a code comparison example.
- Update the `client-download-streaming` code snippet project with the recommended new approach.
- Update code ref and explanation in `client-responses.md`.
> chore: KTOR-7210 Document migration to `kotlinx-io` in the migration guide and update streaming example

- codeSnippets/snippets/client-sse/build.gradle.kts
- codeSnippets/snippets/client-sse/src/main/kotlin/com.example/Application.kt
- codeSnippets/snippets/server-sse/build.gradle.kts
- codeSnippets/snippets/server-sse/src/main/kotlin/com/example/Application.kt
- codeSnippets/snippets/server-sse/src/test/kotlin/com/example/ApplicationTest.kt
- topics/client-server-sent-events.topic
- topics/server-server-sent-events.topic
[KTOR-7776](https://youtrack.jetbrains.com/issue/KTOR-7776) Documentation for Add serialization for SSE
[KTOR-8181](https://youtrack.jetbrains.com/issue/KTOR-8181) Documentation for Add reconnection in ClientSSESession
[KTOR-7954](https://youtrack.jetbrains.com/issue/KTOR-7954) Documentation for Add heartbeat to SSE
Preview on staging:
[Client SSE](https://ktor.staging.kotlin-aws.intellij.net/docs/client-server-sent-events.html#sse-reconnect)
[Server SSE](https://ktor.staging.kotlin-aws.intellij.net/docs/server-server-sent-events.html#heartbeat)
> docs: Add documentation for SSE serialization, reconnection, and heartbeat

- codeSnippets/snippets/upload-file/src/main/kotlin/uploadfile/UploadFile.kt
Fix [KTOR-8431](https://youtrack.jetbrains.com/issue/KTOR-8431/Multipart-form-data-variables-are-places-in-the-wrong-scope).
Run check by following README.md
```console
$ ./gradlew :upload-file:run
$  curl 'http://localhost:8080/upload' -F 'image=@ktor_logo.png;type=image/png"'
is uploaded to 'uploads/ktor_logo.png'
$ ls uploads/ktor_logo.png
uploads/ktor_logo.png
```
> [KTOR-8431] fix: variable scope in multipart formdata

- ktor.tree
- topics/Whats-new-in-Ktor-3-2-0.md
[KTOR-8469](https://youtrack.jetbrains.com/issue/KTOR-8469) Documentation for HttpClientCall: Deprecate `wrapWithContent` and `wrap`
This update modifies:
- What's new in Ktor 3.2.0
> KTOR-8469 Add documentation about wrapWithContent and wrap deprecation

- topics/client-engines.md
I didn't test it yet, but from the changelog and source code it looks like Curl now supports WebSockets and the docs need an update.
> Curl engine supports WebSockets

- topics/whats-new-320.md
[KTOR-8405](https://youtrack.jetbrains.com/issue/KTOR-8405)
Add documentation for configuration file deserialization in the _What's new in Ktor 3.2.0_ topic
To do:
> KTOR-8405 Add typed configuration in the "What's new" doc

- codeSnippets/snippets/json-kotlinx/src/test/kotlin/jsonkotlinx/ApplicationTest.kt
- topics/whats-new-320.md
This PR updates the code in ApplicationTest.kt to make the `client` in `testApplication` mutable as per [KTOR-8545](https://youtrack.jetbrains.com/issue/KTOR-8545).
> KTOR-8545 Make testApplication client mutable

- codeSnippets/snippets/tutorial-kotlin-rpc-app/build.gradle.kts
- codeSnippets/snippets/tutorial-kotlin-rpc-app/src/main/kotlin/Client.kt
- codeSnippets/snippets/tutorial-kotlin-rpc-app/src/main/kotlin/Server.kt
- codeSnippets/snippets/tutorial-kotlin-rpc-app/src/main/kotlin/model/PizzaShop.kt
- topics/tutorial-first-steps-with-kotlin-rpc.topic
Update the https://ktor.io/docs/tutorial-first-steps-with-kotlin-rpc.html tutorial for `0.8.0` release: https://github.com/Kotlin/kotlinx-rpc/releases/tag/0.8.0
> Update kxrpc tutorial to 0.8.0

- topics/server-sessions.md
[KTOR-8110](https://youtrack.jetbrains.com/issue/KTOR-8110)
> KTOR-8110 Document deferred session retrieval 

- codeSnippets/snippets/tutorial-kotlin-rpc-app/README.md
- topics/migrating-3.md
Noticed a small typo when looking at the 2 to 3 migration docs, so fixing it here.
> docs: changing "Applciation" to "Application"

- codeSnippets/snippets/client-parallel-requests/src/main/kotlin/com/example/Application.kt
This PR fixes [KTOR-8630](https://youtrack.jetbrains.com/issue/KTOR-8630/Replace-runBlocking-with-coroutineScope-in-ktor-client-doc).
And I found `.bodyAsText()` is needed in sequential example.
Following README.md of this project, I've confirmed that the app works as expected.
```console
$ ./gradlew :simulate-slow-server:run
$ ./gradlew :client-parallel-requests:run
Response time: 17:38:00.148553
Response time: 17:38:00.147823
```
> KTOR-8630: Use `coroutineScope` instead of `runBlocking`

- codeSnippets/snippets/client-engine-curl/build.gradle.kts
- codeSnippets/snippets/embedded-server-native/build.gradle.kts
- topics/client-engines.md
- topics/client-supported-platforms.md
- topics/server-platforms.md
This updates the Ktor docs to add the missing mentions of linuxArm64, which is actually supported but was never documented.
> Mention linuxArm64 support

- codeSnippets/snippets/tutorial-client-kmm/androidApp/build.gradle.kts
- codeSnippets/snippets/tutorial-client-kmm/gradle/libs.versions.toml
This version (1.5.4) of the Compose Compiler requires Kotlin version 1.9.20 but you appear to be using Kotlin version 2.1.20 which is not known to be compatible.
- Updates compose-compiler version to 2.1.20 (matches Kotlin version)
- Adds `kotlinCompose` plugin per [official migration guide](https://kotlinlang.org/docs/compose-compiler-migration-guide.html)
Since Kotlin 2.0+, Compose Compiler versions align with Kotlin versions and require the new plugin.
tutorial-client-kmm sample only
> fix: Update tutorial-client-kmm sample for Kotlin 2.1.20 Compose compatibility

- ktor.tree
- labels.list
- topics/openapi-spec-generation.md
- topics/server-openapi.md
- topics/server-swagger-ui.md
- topics/whats-new-330.md
[KTOR-8860](https://youtrack.jetbrains.com/issue/KTOR-8860)
- Add a new topic _OpenAPI specification generation_ under _Integrations_.
- Add a section describing the feature in _What's new in Ktor 3.3.0_.
- Remove note from _OpenAPI_ and _SwaggerUI_ plugin topics regarding tools for generating spec and add a link to the new topic in the intro instead.
> docs: feat: KTOR-8860 Documentation for OpenAPI generation build extension preview

- codeSnippets/snippets/static-files/build.gradle.kts
- codeSnippets/snippets/static-files/src/main/kotlin/com/example/Application.kt
- topics/server-static-content.md
- topics/whats-new-330.md
After the addition of [KTOR-8849](https://youtrack.jetbrains.com/issue/KTOR-8849), the `static-files` project stopped compiling.
- add the missing plugin dependency and install it
- replace undeclared variable to match other examples
-  update code block line numbers
> fix: Missing dependency and import in static-files snippet
